# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 12:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.CharField(db_index=True, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('school', models.CharField(choices=[(b'CARTAGENA', (('Colegio Inventado 1', 'Colegio Inventado 1'), ('Colegio Inventado 2', 'Colegio Inventado 2')))], max_length=100)),
                ('level', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('name_victim', models.CharField(max_length=50)),
                ('surname_victim', models.CharField(blank=True, default='', max_length=50)),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('surname', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone_number', models.CharField(blank='True', default='', max_length=9, validators=[django.core.validators.RegexValidator(message='El n\xfamero de tel\xe9fono debe tenerel siguiente formato: 000000000. Hasta 9 d\xedgitos permitidos.', regex='^\\?1?\\d{9}$')])),
                ('img_files', models.ImageField(upload_to='')),
                ('aud_files', models.FileField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
