# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='aud_files',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='report',
            name='img_files',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
